// Importing required components and styles
import Footer from '@/components/Footer/Footer';             // Footer component
import Header from '@/components/Header/Header';             // Header component
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";                                       // Global styles
import "./custom.css";                                       // Global styles

import { Inter } from 'next/font/google';                    // Importing Inter font from Google Fonts
import "../assets/css/fontawesome.min.css";                  // FontAwesome CSS
import { FC, ReactNode } from 'react';

// Define Inter font with Latin subset
const inter = Inter({ subsets: ['latin'] });

// Metadata for the application
export const metadata = {
  title: 'Niotech',                               // Website title
  description: 'Generated by pnpm create next-app --typescript Developed by 3rudit3',  // Website description
}

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
export default RootLayout;