// Importing required components and styles
import Footer from '@/components/Footer/Footer';             // Footer component
import Header from '@/components/Header/Header';
import "./globals.css";                                      // Global styles

import "../assets/css/fontawesome.min.css";                  // FontAwesome CSS
import { FC, ReactNode } from 'react';

// Metadata for the application
export const metadata = {
  title: 'Niotech',                               // Website title
  description: 'Generated by pnpm create next-app --typescript Developed by 3rudit3',  // Website description
}

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
export default RootLayout;