export const servicesCompData = [
  {
    url: "/lighting",
    icon: "/img/icons/light.svg",
    title: "Lighting",
    description: `Discover a smarter way to control your lights and set schedules to turn them on/off. Control them from you smartphone while you’re away.`,
    imgbg: "/img/concepts/bg-1.jpg",
  },
  {
    url: "/home-security",
    icon: "/img/icons/security.svg",
    title: "Home Security",
    description: `                      Our fully integrated systems combine keyless entry, video                      intercoms, sensors and cameras to give you ‘master                      control’ over your entire home right on your smartphone.                    `,
    imgbg: "/img/concepts/bg-2.jpg",
  },
  {
    url: "/interactive-home",
    icon: "/img/icons/interactive.png",
    title: "Interactive Home",
    description: `                      Control most of your Smart Home appliances either                      individually or in pre-set themes just over your voice                      commands. Speak the trigger word and get things done.                    `,
    imgbg: "/img/concepts/bg-3.jpg",
  },
  {
    url: "/multimedia",
    icon: "/img/icons/multimedia.svg",
    title: "Multimedia",
    description: `                      We design a system that delivers control of your audio &                     video system in every room you desire. With smartphone, a                      multi-room music system gives you access to all your                      favorite tunes.                    `,
    imgbg: "/img/concepts/bg-4.jpg",
  },
  {
    url: "/energy-efficiency",
    icon: "/img/icons/energy.svg",
    title: "Energy Efficiency",
    description: `                      Monitor and Control the energy usage patterns of different                      electrical appliances in your home. Trigger lights based                      on presence and day-time schedules for optimum energy                      usage.                    `,
    imgbg: "/img/concepts/bg-5.jpg",
  },
  {
    url: "/protection",
    icon: "/img/icons/protection.svg",
    title: "Protection",
    description: `                      Quick detection of any natural events like sudden rise in                      temperature due to fire, or gas leakage or water leakage                      from any unapproachable area in your home.                    `,
    imgbg: "/img/concepts/bg-6.jpg",
  },
  {
    url: "/climate",
    icon: "/img/icons/climate.svg",
    title: "Climate",
    description: `                      Almost all heating, cooling, air-conditioning and                      ventilation products can be controlled. Zoning your                      heating allows you to divide your home into separate                      manageable areas, giving you the comfort, flexibility and                      control.                    `,
    imgbg: "/img/concepts/bg-7.jpg",
  },
  {
    url: "/surveillances",
    icon: "/img/icons/surveillance.svg",
    title: "Surveillances",
    description: `                      Instantly stream live videos right to your smartphone to                      know what is happening within and outside your house.                    `,
    imgbg: "/img/concepts/bg-8.jpg",
  },
  {
    url: "/ultra-comfort-living",
    icon: "/img/icons/comfort.svg",
    title: "Ultra Comfort Living",
    description: ` Motorized shades offer a host of benefits and add energy                      efficiency, comfort and privacy. Control Pool and spa                      lights, temperature, pumps, jets, cleaners, water features                      and heaters.                    `,
    imgbg: "/img/concepts/bg-9.jpg",
  },
];
